import { StyleSheet, Dimensions } from "react-native";

export const defaultThemeStyle = StyleSheet.create({
    "MainView": {
        "flex": 1,
        "backgroundColor": "black",
        "borderColor": "black",
        "opacity": .8,
        "flexDirection": "column",
        "width": "100%",
        "height": "100%",
        "paddingTop": 10,
        "paddingHorizontal": 0,
        "justifyContent": "flex-start",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center",
        "borderWidth": 12,
        "borderRadius": 0
      },
      "NavView": {
        "flex": .15,
        "backgroundColor": "black",
        "borderColor": "black",
        "opacity": 0.8,
        "flexDirection": "column-reverse",
        "width": "100%",
        "height": "27%",
        "paddingVertical": 0,
        "paddingHorizontal": 0,
        "justifyContent": "flex-end",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center",
        "borderWidth": 12,
        "borderRadius": 52
      },
      "InfoView": {},
      "BasicText": {
        "textAlignVertical": "center",
        "flex": .07,
        "flexWrap": "wrap",
        "flexGrow": .3,
        "color": "white",
        "backgroundColor": "black",
        "fontSize": 20,
        "fontFamily": "serif",
        "textAlign": "center",
        "letterSpacing": 10,
        "lineHeight": 22,
        "textShadowColor": "white",
        "textShadowRadius": 13,
        "borderColor": "white",
        "opacity": .8,
        "width": "100%",
        "height": "15%",
        "paddingTop": 10,
        "paddingHorizontal": 10,
        "justifyContent": "center",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center",
        "borderWidth": 10,
        "borderRadius": 50
      },
      "OfferingsText": {
        "flex": .2,
        "flexGrow": .3,
        "flexBasis": "100%",
        "color": "white",
        "backgroundColor": "black",
        "fontSize": 15,
        "fontFamily": "serif",
        "textAlign": "center",
        "letterSpacing": 10,
        "lineHeight": 25,
        "textShadowColor": "white",
        "textShadowRadius": 13,
        "borderColor": "white",
        "opacity": .8,
        // "width": "100%",
        // "minWidth": "100%",
        "height": "15%",
        "paddingTop": 20,
        "paddingHorizontal": 4,
        "justifyContent": "center",
        "alignContent": "stretch",
        "alignItems": "stretch",
        "alignSelf": "stretch",
        "borderWidth": 10,
        "borderRadius": 50
      },
      "TitleText": {
        "textAlignVertical": "center",
        "flex": .20,
        "flexShrink": 2,
        "color": "black",
        "backgroundColor": "#2D63C8",
        "fontSize": 25,
        "fontFamily": "serif",
        "textAlign": "center",
        "letterSpacing": 10,
        "lineHeight": 45,
        "textShadowColor": "white",
        "textShadowRadius": 13,
        "borderColor": "white",
        "opacity": 1,
        "width": "100%",
        "height": "25%",
        "paddingVertical": 15,
        "paddingHorizontal": 10,
        "justifyContent": "center",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center",
        "borderWidth": 10,
        "borderRadius": 50
      },
      "Modal": {},
      "MenuButton": {},
      "SyncButton": {},
      "InfoText": {},
      "titleText": {},
      "BasicButtonView": {},
      "BasicInputText": {
        "flex": .2,
        "color": "black",
        "backgroundColor": "#2D63C8",
        "fontSize": 30,
        "fontFamily": "serif",
        "textAlign": "center",
        "letterSpacing": 0,
        "lineHeight": 8,
        "textShadowColor": "white",
        "textShadowRadius": 12,
        "borderColor": "white",
        "opacity": 1,
        "width": "80%",
        "height": "21%",
        "paddingVertical": 10,
        "paddingHorizontal": 0,
        "justifyContent": "center",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center",
        "borderWidth": 10,
        "borderRadius": 50
      },
      "ProblemTextInput": {
        "flex": .9,
        "flexDirection": "column",
        "flexWrap": 'wrap',
        "color": "black",
        "backgroundColor": "#2D63C8",
        "fontSize": 30,
        "fontFamily": "serif",
        "textAlign": "center",
        "letterSpacing": 0,
        "lineHeight": 35,
        "textShadowColor": "white",
        "textShadowRadius": 12,
        "borderColor": "white",
        "opacity": 1,
        "width": "100%",
        "height": "40%",
        "paddingVertical": 10,
        "paddingHorizontal": 15,
        "justifyContent": "center",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center",
        "borderWidth": 10,
        "borderRadius": 20
      },
      "LoginButtonView": {
        "flex": .2,
        "flexGrow": .3,
        "backgroundColor": "#2D63C8",
        "borderColor": "white",
        "opacity": 1,
        "flexDirection": "column",
        "width": "50%",
        "height": "30%",
        "paddingVertical": 0,
        "paddingHorizontal": 10,
        "justifyContent": "center",
        "alignContent": "center",
        "alignItems": "center",
        "alignSelf": "center",
        "borderWidth": 10,
        "borderRadius": 50
      },
      "ReservationInfoView": {
        "flex": 1,
        "backgroundColor": "#2D63C8",
        "borderColor": "white",
        "opacity": 1,
        "flexDirection": "column",
        "width": "100%",
        "height": "30%",
        "paddingVertical": 0,
        "paddingHorizontal": 0,
        "justifyContent": "space-around",
        "alignContent": "center",
        "alignItems": "stretch",
        "alignSelf": "center",
        "borderWidth": 10,
        "borderRadius": 50
    },
    "FlatlistView": {
        "flex": .8,
        "backgroundColor": "#2D63C8",
        "borderColor": "white",
        "opacity": 1,
        "flexDirection": "column",
        "width": "100%",
        "height": "70%",
        "paddingVertical": 10,
        "paddingHorizontal": 10,
        "justifyContent": "center",
        "alignContent": "center",
        "alignItems": "stretch", //needed to make text views max width
        "alignSelf": "center",
        "borderWidth": 10,
        "borderRadius": 50
    }
      
})




// "MainView": {
//     "backgroundColor": "grey",
//     "borderColor": "#663300",
//     "opacity": 1,
//     "width": 500,
//     "height": 273,
//     "paddingVertical": 147,
//     "paddingHorizontal": 0,
//     "justifyContent": "center",
//     "alignContent": "center",
//     "alignItems": "center",
//     "alignSelf": "center",
//     "borderWidth": 14,
//     "borderRadius": 44
//   },
//   "NavView": {
//     "backgroundColor": "grey",
//     "borderColor": "black",
//     "opacity": 1,
//     "width": 320,
//     "height": 100,
//     "paddingVertical": 0,
//     "paddingHorizontal": 0,
//     "justifyContent": "center",
//     "alignContent": "center",
//     "alignItems": "center",
//     "alignSelf": "center",
//     "borderWidth": 0,
//     "borderRadius": 0
//   },
//   "InfoView": {},
//   "Text": {
//     "color": "#663300",
//     "backgroundColor": "#2D63C8",
//     "fontSize": 15,
//     "fontFamily": "serif",
//     "textAlign": "center",
//     "letterSpacing": 0,
//     "lineHeight": 24,
//     "borderColor": "black",
//     "opacity": 1,
//     "width": 380,
//     "height": 53,
//     "paddingVertical": 0,
//     "paddingHorizontal": 0,
//     "justifyContent": "center",
//     "alignContent": "center",
//     "alignItems": "center",
//     "alignSelf": "center",
//     "borderWidth": 7,
//     "borderRadius": 4
//   },
//   "TitleText": {},
//   "Modal": {},
//   "MenuButton": {},
//   "SyncButton": {},
//   "InfoText": {},
//   "titleText": {}
